export const products = [
    {
        title: "Magnetite",
        category: 8,
        price: 89.0,
        img: "/src/assets/images/albums/Album1.png",
        band: "Scalene",
        year: 2017,
        id: 0,
    },
    {
        title: "Acabou o Chorare",
        category: 2,
        price: 66.0,
        img: "/src/assets/images/albums/Album2.png",
        band: "Novos Baianos",
        year: 1972,
        id: 1,
    },
    {
        title: "Nirvana Discografia",
        category: 8,
        price: 50.0,
        img: "/src/assets/images/albums/Album3.png",
        band: "Nirvava",
        year: 1990,
        id: 2,
    },
    {
        title: "Both Sides",
        category: 1,
        price: 22.0,
        img: "/src/assets/images/albums/Album4.png",
        band: "Phil Collins",
        year: 1993,
        id: 3,
    },
];

export const categories = [
    "Todos",
    "Pop",
    "MPB",
    "Forró",
    "Samba",
    "Baião",
    "Rap",
    "Hip-Hop",
    "Rock",
    "Reggae",
    "Country",
    "Gospel",
];
